function init_conf {
# ExaGear components and their settings
    EXAGEAR_USE_OPT="y"
    EXAGEAR_USE_CB="n"
    EXAGEAR_USE_INTERPRETER="n"
    EXAGEAR_ENABLE_SW_PROF="n"
    EXAGEAR_ENABLE_PTRACE="n"
    EXAGEAR_CFG_BUILDER_MODE="none"

# Unsafe optimizations
    EXAGEAR_DISABLE_NATIVE_RETURN_ADDR_OPT="n"
    EXAGEAR_DISABLE_THP_PREALLOC="n"
    EXAGEAR_DISABLE_THP_MADVISE="n"
    EXAGEAR_DISABLE_FLAGS_ON_CALL_RET_OPT="n"
    EXAGEAR_DISABLE_JIT_STORE_OPT="n"
    EXAGEAR_FAST_MATH="n"
    EXAGEAR_X86_DISABLE_SSE_PRESERVE="n"
    EXAGEAR_X86_ENABLE_VZEROUPPER="n"

# x86 guest options
    EXAGEAR_X86_PRECISE_FP="n"
    EXAGEAR_X86_PRECISE_80BIT_FP="n"
    EXAGEAR_X86_ENABLE_AVX="n"
    EXAGEAR_X86_ENABLE_AVX512="n"

# ARM host options
    EXAGEAR_ENABLE_SVE="n"
    EXAGEAR_ENABLE_SVE512="n"

# Strong memory ordering
    EXAGEAR_SMO_MODE="fbase"
    EXAGEAR_SMO_SEVERITY="smart"
    EXAGEAR_DISABLE_SMO_IN_JIT="n"
    EXAGEAR_SMO_PATTERNS=""
    EXAGEAR_SMO_PATTERNS_EXCL=""
    EXAGEAR_SMO_CONFIG=""
    EXAGEAR_SMO_LIBC_USE_BLACKLIST="n"
    EXAGEAR_SMO_DISABLE_LIBC_WARN="n"

# Passthrough
    EXAGEAR_PT_CONFIG=""
}



if [ "${EXAGEAR_APP_NAME}" == "PERFORMANCE_FIRST" ]; then
    init_conf

    EXAGEAR_USE_OPT="y"

    EXAGEAR_DISABLE_NATIVE_RETURN_ADDR_OPT="n"
    EXAGEAR_DISABLE_THP_PREALLOC="n"
    EXAGEAR_DISABLE_THP_MADVISE="n"
    EXAGEAR_DISABLE_FLAGS_ON_CALL_RET_OPT="n"
    EXAGEAR_DISABLE_JIT_STORE_OPT="n"
    EXAGEAR_FAST_MATH="y"
    EXAGEAR_X86_DISABLE_SSE_PRESERVE="y"
    EXAGEAR_X86_ENABLE_VZEROUPPER="n"

    EXAGEAR_X86_PRECISE_FP="n"
    EXAGEAR_X86_PRECISE_80BIT_FP="n"

    EXAGEAR_X86_ENABLE_AVX="n"
    EXAGEAR_ENABLE_SVE="n"

    EXAGEAR_X86_ENABLE_AVX512="n"
    EXAGEAR_ENABLE_SVE512="n"

    EXAGEAR_SMO_MODE="fbase"

elif [ "${EXAGEAR_APP_NAME}" == "FUNCTION_FIRST" ]; then
    init_conf

    EXAGEAR_USE_OPT="n"

    EXAGEAR_DISABLE_NATIVE_RETURN_ADDR_OPT="y"
    EXAGEAR_DISABLE_THP_PREALLOC="y"
    EXAGEAR_DISABLE_THP_MADVISE="y"
    EXAGEAR_DISABLE_FLAGS_ON_CALL_RET_OPT="y"
    EXAGEAR_DISABLE_JIT_STORE_OPT="y"
    EXAGEAR_FAST_MATH="n"
    EXAGEAR_X86_DISABLE_SSE_PRESERVE="n"
    EXAGEAR_X86_ENABLE_VZEROUPPER="y"

    EXAGEAR_X86_PRECISE_FP="y"
    EXAGEAR_X86_PRECISE_80BIT_FP="y"

    EXAGEAR_X86_ENABLE_AVX="n"
    EXAGEAR_X86_ENABLE_AVX512="n"

    EXAGEAR_ENABLE_SVE="n"
    EXAGEAR_ENABLE_SVE512="n"

    EXAGEAR_SMO_MODE="all"

elif [ "${EXAGEAR_APP_NAME}" == "MODE1" ]; then
    init_conf
    EXAGEAR_USE_OPT="y"
    EXAGEAR_FAST_MATH="y"

elif [ "${EXAGEAR_APP_NAME}" == "MODE2" ]; then
    init_conf
    EXAGEAR_USE_OPT="y"
    EXAGEAR_FAST_MATH="y"
    EXAGEAR_SMO_MODE="all"

elif [ "${EXAGEAR_APP_NAME}" == "MODE3" ]; then
    init_conf
    EXAGEAR_USE_OPT="y"
    EXAGEAR_FAST_MATH="n"
    EXAGEAR_X86_PRECISE_FP="y"
    EXAGEAR_X86_PRECISE_80BIT_FP="y"

elif [ "${EXAGEAR_APP_NAME}" == "MODE4" ]; then
    init_conf
    EXAGEAR_USE_OPT="y"
    EXAGEAR_FAST_MATH="y"
    EXAGEAR_X86_ENABLE_AVX="y"
    EXAGEAR_X86_DISABLE_SSE_PRESERVE="y"
    EXAGEAR_ENABLE_SVE="y"
elif [ "${EXAGEAR_APP_NAME}" == "MODE5" ]; then
    init_conf
    EXAGEAR_USE_OPT="n"
    EXAGEAR_FAST_MATH="n"
    EXAGEAR_X86_PRECISE_FP="y"
    EXAGEAR_X86_PRECISE_80BIT_FP="y"
fi
