#!/bin/bash
CUR_SESSION_LEADER_ID=$(ps -o sid= -p $$)
CUR_PPID=$PPID
if [[ ${CUR_PPID} == ${CUR_SESSION_LEADER_ID} ]]; then
    echo -e "\e[1;31m        __       ___      .______      ____    ____  __       _______. ";
    echo -e "\e[1;32m       |  |     /   \     |   _  \     \   \  /   / |  |     /       | ";
    echo -e "\e[1;33m       |  |    /  ^  \    |  |_)  |     \   \/   /  |  |    |   (----\` ";
    echo -e "\e[1;34m .--.  |  |   /  /_\  \   |      /       \      /   |  |     \   \ ";
    echo -e "\e[1;35m |  \`--'  |  /  _____  \  |  |\  \----.   \    /    |  | .----)   | ";
    echo -e "\e[1;36m  \______/  /__/     \__\ | _| \`._____|    \__/     |__| |_______/ ";
    echo -e "\e[0m"
fi
#prevent whitespace problems
python3 ./src/jarvis.py "$@"
